# Vector DB comparision

## [Vector DB Dashboard](https://superlinked.com/vector-db-comparison) -> Click to get more information

|       **Feature**      |      **FAISS**      |                        **ChromaDB**                       |      **Pinecone**      |                          **Weaviate**                          |                    **Qdrant**                    |            LanceDB            |
|:----------------------:|:-------------------:|:---------------------------------------------------------:|:----------------------:|:--------------------------------------------------------------:|:------------------------------------------------:|:-----------------------------:|
| **Type**               | Library             | Library + DB                                              | Managed Cloud DB       | Managed DB + OSS                                               | Managed DB + OSS                                 | Managed DB + OSS              |
| **Hosting**            | Local               | Local (some cloud support)                                | Cloud-only             | Cloud & Self-host                                              | Cloud & Self-host                                | Cloud & Self-host             |
| **Persistant Storage** | No (in-memory)      | Yes                                                       | Yes                    | Yes                                                            | Yes                                              | Yes (s3)                      |
| **Scalability**        | Manual              | Limited                                                   | Auto-scaling           | Auto-scaling                                                   | Auto-scaling                                     | Auto-scaling                  |
| **API Access**         | No REST API         | Python API                                                | REST/gRPC API          | REST/gRPC API                                                  | REST/gRPC API                                    | Pandas Style API              |
| **Indexing Option**    | IVF, HNSW, PQ, Flat | HNSW, SPANN                                               | Proprietery            | HNSW, Flat, IVF, Flat-BQ                                       | HNSW, IVF, PQ                                    | HNSW, IVF, PQ                 |
| **BM-25**              | No                  | No                                                        | No                     | Yes                                                            | No                                               | Yes                           |
| **Hybrid search**      | No                  | No                                                        | Yes                    | Yes                                                            | Yes                                              | Yes                           |
| **Metadata Filtering** | Manual              | Built-in                                                  | Built-in               | Built-in                                                       | Built-in                                         | Built-in (limited)            |
| **Replication**        | No                  | No                                                        | Yes                    | Yes                                                            | Yes                                              | NA                            |
| **Embeddings Storage** | Vectors only        | Vectors + Metadata + Documents                            | Vectors + Metadata     | Vectors + Metadata + Schema                                    | Vectors +  Payload (Custom  metadata)            | tabular + vector              |
| **Integrations**       | Custom              | Langchain, Lllamaindex                                    | Langchain, Lllamaindex | Langchain, Lllamaindex                                         | Langchain, Lllamaindex                           | Langchain, Lllamaindex        |
| **License**            | MIT                 | Apache 2.0                                                | Proprietery SaaS       | BSD                                                            | Apache 2.0                                       | Apache 2.0                    |
| **Best For**           | Fast local search   | Embedding + metadata                                      | Production Saas        | Knowledge graph &  vector search                               | Vector Search  with filtering                    | Tabular data +  Vector search |
| **Docker image**       | No                  | [chromadb](https://hub.docker.com/r/chromadb/chroma/tags) | NA                     | [weaviate](https://hub.docker.com/r/semitechnologies/weaviate) | [qdrant](https://hub.docker.com/r/qdrant/qdrant) | NA                            |
| **Dev Language**       | C++                 | rust                                                      | rust                   | go                                                             | rust                                             | rust                          |
| **Multi-tenant**       | No                  | Yes                                                       | Yes (via namespace)    | Yes                                                            | Yes (via collection/metadata)                    | No                            |

## Comparing different vector db

### Step 1 - Prepare test data

In [ ]:
sentences = [
	"Artificial intelligence is transforming modern healthcare through diagnostic tools.",
	"Machine learning algorithms can predict patient outcomes with high accuracy.",
	"Neural networks require large amounts of training data to be effective.",
	"Cloud computing enables scalable AI deployment across industries.",
	"Natural language processing allows computers to understand human speech.",
	"Deep learning models excel at image recognition tasks.",
	"Data privacy remains a major concern in AI implementation.",
	"Quantum computing promises to revolutionize complex calculations.",
	"Robotics automation is changing manufacturing processes worldwide.",
	"Computer vision systems can identify objects in real-time video.",
	"Ethical AI development requires careful consideration of bias.",
	"The Internet of Things connects everyday devices to the cloud.",
	"Blockchain technology provides secure decentralized transactions.",
	"5G networks enable faster data transfer for mobile applications.",
	"Virtual reality creates immersive digital experiences for users.",
	"Cybersecurity threats continue to evolve with advancing technology.",
	"Big data analytics helps businesses make informed decisions.",
	"Autonomous vehicles use sensors and AI to navigate roads safely.",
	"Edge computing processes data closer to the source for reduced latency.",
	"Augmented reality overlays digital information onto the real world.",
	"Python is the most popular programming language for data science.",
	"Reinforcement learning allows AI to learn through trial and error.",
	"Semiconductor chips are essential components in all computing devices.",
	"Digital transformation affects every industry in the modern economy.",
	"AI ethics committees are being formed to guide responsible development.",
]

In [ ]:
queries = [
	"AI in healthcare",
	"Machine learning applications",
	"Technology security concerns",
	"Neural networks and data requirements",
	"Real-time computer vision systems",
]

In [3]:
import os
from dotenv import load_dotenv, find_dotenv

load_dotenv(find_dotenv())
EURI_API_KEY = os.getenv("EURI_API_KEY")

In [4]:
import requests
import numpy as np

In [5]:
def generate_embeddings(text: str) -> np.ndarray:
	url = "https://api.euron.one/api/v1/euri/embeddings"
	headers = {
		"Content-Type": "application/json",
		"Authorization": f"Bearer {EURI_API_KEY}",
	}
	payload = {"input": text, "model": "text-embedding-3-small"}

	response = requests.post(url, headers=headers, json=payload)
	data = response.json()

	embedding = np.array(data["data"][0]["embedding"], dtype=np.float32)

	return embedding

In [6]:
text = "The weather is sunny today."

embedding = generate_embeddings(text)

embdding shape: (1536,) and embedding type: <class 'numpy.ndarray'>


In [8]:
print(f"embedding shape: {embedding.shape} and embedding type: {embedding.dtype}")

embedding shape: (1536,) and embedding type: float32


In [9]:
embeddings = []
for i in sentences:
	emb = generate_embeddings(text=i)
	embeddings.append(emb)

In [11]:
embeddings

[array([ 0.0098142 , -0.02956349,  0.0170677 , ...,  0.00462685,
        -0.03077241,  0.02712368], shape=(1536,), dtype=float32),
 array([-0.00839084, -0.00398261,  0.03710102, ..., -0.00083121,
        -0.01360887, -0.00225663], shape=(1536,), dtype=float32),
 array([ 0.00686272,  0.0106579 ,  0.03276936, ..., -0.02073997,
         0.00420348,  0.01802838], shape=(1536,), dtype=float32),
 array([-0.00989157, -0.03057791,  0.04363609, ..., -0.01714974,
        -0.01270996,  0.04276554], shape=(1536,), dtype=float32),
 array([-0.03052658,  0.0204996 , -0.0008052 , ..., -0.00183322,
         0.02163397,  0.03516533], shape=(1536,), dtype=float32),
 array([ 0.01001777, -0.03060824, -0.0151873 , ...,  0.01738751,
         0.01140021,  0.0041327 ], shape=(1536,), dtype=float32),
 array([ 0.03143589,  0.00471424,  0.03636701, ..., -0.01519287,
         0.03123043,  0.00258827], shape=(1536,), dtype=float32),
 array([-0.02738322,  0.01016155, -0.01991831, ..., -0.02638313,
         0.0295024

In [12]:
len(embeddings[0])

1536

In [14]:
embeddings_array = np.vstack(embeddings)
embeddings_array.shape

(25, 1536)

In [ ]:
dimension = embeddings_array.shape[1]
dimension

### Running in FAISS

In [ ]:
import faiss

In [ ]:
index = faiss.IndexFlatL2(dimension)
index

In [19]:
index.add(embeddings_array)
index.ntotal

25

In [20]:
query = queries[0]
query

'AI in healthcare'

In [22]:
query_vec = generate_embeddings(text=query).reshape(1, -1)
query_vec.shape

(1, 1536)

In [ ]:
distance, indices = index.search(query_vec, 2)

In [ ]:
print(
	f"Query: {query}\n"
	f"Top 2 most similar sentences:\n"
	f"{sentences[indices[0][0]]}\n"
	f"{sentences[indices[0][1]]}\n"
)

In [ ]:
# save index to disk
faiss.write_index(index, "../data/faiss_index.faiss")